name: pruebaWfs

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Installdependences
        run: npm install
      - name: Lint
        run: npm run eslint
    



        
